teams = [
    {'team': '0', 'title': '0', 'img': '-1'},
    {'team': 'Arsenal', 'title': 'Arsenal', 'img': 'Arsenal'},
    {'team': 'Aston Villa', 'title': 'Aston Villa', 'img': 'Aston_Villa'},
    {'team': 'Bournemouth', 'title': 'Bournemouth', 'img': 'Bournemouth'},
    {'team': 'Brentford', 'title': 'Brentford', 'img': 'Brentford'},
    {'team': 'Brighton', 'title': 'Brighton', 'img': 'Brighton'},
    {'team': 'Burnley', 'title':'Burnley','img':'Burnley'},
    {'team': 'Chelsea', 'title': 'Chelsea', 'img': 'Chelsea'},
    {'team': 'Crystal Palace', 'title': 'Crystal Palace', 'img': 'Crystal_Palace'},
    {'team': 'Everton', 'title': 'Everton', 'img': 'Everton'},
    {'team': 'Fulham', 'title': 'Fulham', 'img': 'Fulham'},
    {'team': 'Liverpool', 'title': 'Liverpool', 'img': 'Liverpool'},
    {'team': 'Luton','title':'Luton','img':'Luton'},
    {'team': 'Man City', 'title': 'Manchester City', 'img': 'Man_City'},
    {'team': 'Man Utd', 'title': 'Manchester United', 'img': 'Man_Utd'},
    {'team': 'Newcastle', 'title': 'Newcastle United', 'img': 'Newcastle'},
    {'team': 'Nott\'m Forest', 'title': 'Nottingham Forest', 'img': 'Forest'},
    {'team': 'Sheffield Utd','title':'Sheffield United','img':'Sheffield_Utd'},
    {'team': 'Spurs', 'title': 'Tottenham', 'img': 'Spurs'},
    {'team': 'West Ham', 'title': 'West Ham', 'img': 'West_Ham'},
    {'team': 'Wolves', 'title': 'Wolverhampton Wanderers', 'img': 'Wolves'}
]